name: node-16 (nightly)

# Build and push to docker hub (if upstream changed in the last day)
on:
  # run nightly
  schedule:
    - cron:  '14 14 * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      UPSTREAM_REPO: https://hub.docker.com/v2/repositories/library/node/tags/16-alpine
      DOCKER_REPO: alpine-node-git-yarn
      DOCKER_TAG: node-16
    steps:
      - name: Check Upstream
        id: check-upstream
        run: |
          LAST_PUSHED=$(curl -s -X GET ${UPSTREAM_REPO} | jq -r ".tag_last_pushed")
          if [ $(date --date "${LAST_PUSHED}" +'%s') -ge $(date --date "1 days ago" +'%s') ]; then
            echo "Upstream changed, building image"
            echo "::set-output name=upstream::changed"
          else
            echo "No upstream change, skipping"
          fi

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref:
            node-16
        if: steps.check-upstream.outputs.upstream == 'changed'

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        if: steps.check-upstream.outputs.upstream == 'changed'

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
        if: steps.check-upstream.outputs.upstream == 'changed'

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        if: steps.check-upstream.outputs.upstream == 'changed'

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_REPO }}:${{ env.DOCKER_TAG}}
        if: steps.check-upstream.outputs.upstream == 'changed'
